<main id="blog">
    <ul>
        <?php foreach($articles as $key => $article): ?>
            <li>
                <article>
                    <header>
                        <h2><?= htmlspecialchars($article["titre"]) ?></h2>
                    </header>
                    <section>
                        <p><?= htmlspecialchars($article["resume"]) ?></p>
                    </section>
                    <footer>
                        <a href="?route=article&id=<?= $key ?>">Lire l'article complet</a>
                    </footer>
                </article>
            </li>
        <?php endforeach; ?>
    </ul>
</main>