<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body>
        <form action="logic/register.php" method="POST">
            
            <input type="text" name="first_name" id="first_name" placeholder="Votre prenom"/>
            
            <input type="text" name="last_name" id="last_name" placeholder="Votre nom"/>
            
            <input type="email" name="email" id="email" placeholder="Votre email"/>
            
            <input type="password" name="password" id="password" placeholder="Votre mot de passe"/>
            
            <input type="submit" value="Soumettre"/>
            
        </form>
    </body>
</html>